### ISSUE TITLE
jarファイルとしてmodsフォルダに入れるとワールド起動時にエラーで落ちる

### ISSUE THREAD

**Issue by takecx** [takecx/RemoteControllerMod#5]
エラー内容

```
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 21/06/04 22:47
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/java_websocket/server/WebSocketServer
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_74] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_74] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74] {}
	at com.github.takecx.remotecontrollermod.Remotecontrollermod.onServerStarting(Remotecontrollermod.java:131) ~[?:0.01] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_0_Remotecontrollermod_onServerStarting_FMLServerStartingEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:102) ~[?:?] {re:classloading}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:62) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74] {}
Caused by: java.lang.ClassNotFoundException: org.java_websocket.server.WebSocketServer
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_74] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74] {}
	... 15 more
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74] {}
		at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_74] {}
		at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_74] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74] {}
		at com.github.takecx.remotecontrollermod.Remotecontrollermod.onServerStarting(Remotecontrollermod.java:131) ~[?:0.01] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_0_Remotecontrollermod_onServerStarting_FMLServerStartingEvent.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:102) ~[?:?] {re:classloading}
		at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:62) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) ~[?:?] {re:classloading,pl:accesstransformer:B}
		at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
		at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1331830736 bytes (1270 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		remotecontrollermod-0.01.jar                      |Remotecontrollermod           |remotecontrollermod           |0.01                |DONE      |NOSIGNATURE
	Crash Report UUID: f839b66e-479e-4272-aad1-8e6afc6c1b7c
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:forge, mod:remotecontrollermod
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
```

**Comment by takecx** [comment]
`Java_Websocket`について、GithubのReleaseから`1.5.2`のソースコードをダウンロードしてきて適切な場所に配置した

**Comment by takecx** [comment]
`slf4j`というログ用のライブラリ？についても必要ぽかったので、同じようにGithubから`1.7.25`のソースコードをダウンロードしてきて配置した
- `slf4j-api`
- `slf4j-simple`

**Comment by takecx** [comment]
これでjarファイルにビルドしても動くようになったぽい

こんなやり方であってるのかどうかはよくわからないが、一旦動いたのでcloseする
